version: "3.8"
services:
  redis:
    restart: unless-stopped
    image: redis/redis-stack-server
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - redis-data:/data

  postgresql:
    image: paradedb/paradedb:latest-pg17
    restart: unless-stopped
    environment:
      POSTGRES_DB: gogol
      POSTGRES_USER: gogol
      POSTGRES_PASSWORD: password123
      PGDATA: /var/lib/postgresql/data
      TZ: Europe/Paris
      PGTZ: Europe/Paris
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U gogol
      interval: 10s
      timeout: 5s
      retries: 5

  init:
    restart: always
    environment:
      LOG_LEVEL: INFO
      DB_HOST: postgresql
      DB_NAME: gogol
      DB_USER: gogol
      DB_PASSWORD: password123
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      PAGERANK_DELAY: 30
      PYTHONUNBUFFERED: 1
    image: buco7854/gogol-init:latest
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy

  server:
    restart: unless-stopped
    environment:
      LOG_LEVEL: DEBUG
      DB_HOST: postgresql
      DB_NAME: gogol
      DB_USER: gogol
      DB_PASSWORD: password123
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      PYTHONUNBUFFERED: 1
      GUNICORN_CMD_ARGS: --bind=0.0.0.0:5000 --workers=3 --forwarded-allow-ips=192.168.1.61
    ports:
      - 5000:5000
    image: buco7854/gogol-server:latest
    depends_on:
      init:
        condition: service_started
      redis:
        condition: service_healthy
      postgresql:
        condition: service_healthy
  crawler:
    stop_grace_period: 20s
    restart: unless-stopped
    environment:
      LOG_LEVEL: INFO
      DB_HOST: postgresql
      DB_NAME: gogol
      DB_USER: gogol
      DB_PASSWORD: password123
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      BROWSER_HEADLESS: true
      BROWSER_REMOTE: false
      PYTHONUNBUFFERED: 1
      CRAWLER_BATCH_SIZE: 15
      CRAWLER_QUEUE_MIN_SIZE: 5
      CRAWLER_DELETION_CANDIDATES_MAX_SIZE: 5
      CRAWLER_FAILED_TRIES_MAX_SIZE: 5
    image: buco7854/gogol-crawler:latest
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      init:
        condition: service_started
      redis:
        condition: service_healthy
      postgresql:
        condition: service_healthy

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      ADMINER_PLUGINS: 'tables-filter tinymce'
      ADMINER_DESIGN: 'dracula'
      ADMINER_DEFAULT_SERVER: 'postgresql'
    networks:
      - default

networks: {}

volumes:
  pgdata: null
  redis-data: null
